apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postfix-container-env
  namespace: postfix
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: RELAYHOST_PASSWORD
      remoteRef:
        key: smtprelay-app-password
