# https://external-secrets.io/latest/examples/gitops-using-fluxcd/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repositories.yaml
  - deployment-crds.yaml
  - release.yaml
