apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hoppscotch
resources:
  - ../../base/hoppscotch/

configMapGenerator:
  - name: hoppscotch-values
    files:
      - values.yaml=values.yaml