apiVersion: v1
kind: Service
metadata:
  name: adguard-dns-secure
  namespace: adguard
spec:
  selector:
    app: adguard-home
  ports:
    - port: 443
      targetPort: 443
      name: dns-https
    - port: 853
      targetPort: 853
      name: dns-tls
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-api
  namespace: adguard
spec:
  clusterIP: None
  selector:
    app: adguard-home
  ports:
    - port: 5380
      name: http-api
