apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  namespace: adguard
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dns.6541333.xyz
    io.cilium/lb-ipam-ips: "10.134.20.53"
  labels:
    cilium-lb-pool: static-ip-pool
spec:
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 3600
  selector:
    app: adguard-home
  ports:
    - port: 53
      targetPort: 53
      name: dns-tcp
      protocol: TCP
    - port: 53
      targetPort: 53
      name: dns-udp
      protocol: UDP
    - port: 443
      targetPort: 443
      name: dns-https
    - port: 853
      targetPort: 853
      name: dns-tls
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-api
  namespace: adguard
spec:
  clusterIP: None
  selector:
    app: adguard-home
  ports:
    - port: 5380
      name: http-api
