apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  namespace: adguard
  annotations:
    io.cilium/lb-ipam-ips: '10.134.20.53'
  labels:
    cilium-lb-pool: static-ip-pool
spec:
  selector:
    app: adguard-home
  ports:
    - port: 53
      targetPort: 53
      name: dns-tcp
      protocol: TCP
    - port: 53
      targetPort: 53
      name: dns-udp
      protocol: UDP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns-secure
  namespace: adguard
spec:
  selector:
    app: adguard-home
  ports:
    - port: 443
      targetPort: 443
      name: dns-https
    - port: 853
      targetPort: 853
      name: dns-tls
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-api
  namespace: adguard
spec:
  clusterIP: None
  selector:
    app: adguard-home
  ports:
    - port: 5380
      name: http-api
