apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: adguard-https-passthrough
  namespace: adguard
spec:
  parentRefs:
    - name: dns-gateway
      namespace: cilium-gateway
      sectionName: dns-https
  hostnames:
    - dns.6541333.xyz
  rules:
    - backendRefs:
        - name: adguard-dns-secure
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: adguard-tls
  namespace: adguard
spec:
  parentRefs:
    - name: dns-gateway
      namespace: cilium-gateway
      sectionName: dns-tls
  hostnames:
    - dns.6541333.xyz
  rules:
    - backendRefs:
        - name: adguard-dns-secure
          port: 853
