apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: cloudflare-secret
      remoteRef:
        key: authelia-cloudflare-secret
    - secretKey: db-password
      remoteRef:
        key: authelia-db-password
    - secretKey: oidc-hmac
      remoteRef:
        key: authelia-oidc-hmac
    - secretKey: session-secret
      remoteRef:
        key: authelia-session-secret
    - secretKey: jwt-secret
      remoteRef:
        key: authelia-jwt-secret
    - secretKey: storage-encryption-key
      remoteRef:
        key: authelia-storage-encryption-key
    - secretKey: valkey-password
      remoteRef:
        key: valkey-authelia-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-oidc-key
  namespace: authelia
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: authelia-oidc-key
    template:
      engineVersion: v2
      data:
        oidc-private.pem: |
          {{ .oidc_key }}

  data:
    - secretKey: oidc_key
      remoteRef:
        key: authelia-oidc-private-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: authelia
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: credentials.json
      remoteRef:
        key: cloudflare-tunnel-authelia
