apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-container-env
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: ORIGIN_PASSWORD
      remoteRef:
        key: adguard-password
    - secretKey: REPLICA1_PASSWORD
      remoteRef:
        key: adguard-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-container-env
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: RCLONE_CONFIG_R2_ACCESS_KEY_ID
      remoteRef:
        key: rclone-r2-access-key-id
    - secretKey: RCLONE_CONFIG_R2_SECRET_ACCESS_KEY
      remoteRef:
        key: rclone-r2-secret-access-key
    - secretKey: RCLONE_CONFIG_CRYPT_PASSWORD
      remoteRef:
        key: adguard-rclone-encrypt-password

