apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-db-production-cnpg-v1
spec:
  description: Postgres cluster for the commafeed application
  imageName: quay.io/enterprisedb/postgresql:17.4
  instances: 3

  monitoring:
    enablePodMonitor: true

  inheritedMetadata:
    labels:
      app: commafeed-database
      policy-type: "database"

  storage:
    size: 5Gi

  bootstrap:
    initdb:
      database: commafeed
      owner: commafeed
      secret:
        name: commafeed-db-creds

  # handy: resources can be used to trigger a redeploy
  resources:
    requests:
      memory: 600Mi

  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: commafeed-db-lb
              labels:
                cilium-lb-pool: postgres-pool
              annotations:
                external-dns.alpha.kubernetes.io/hostname: commafeed-db.6541333.xyz
            spec:
              type: LoadBalancer
