apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-db-production-cnpg-v1
spec:
  description: Postgres cluster for the commafeed application
  imageName: quay.io/enterprisedb/postgresql:17.4
  instances: 3

  monitoring:
    enablePodMonitor: true

  inheritedMetadata:
    labels:
      app: commafeed-database
      policy-type: "database"

  storage:
    size: 5Gi

  bootstrap:
    recovery:
      source: cluster-backup
      database: commafeed
      owner: commafeed
      secret:
        name: commafeed-db-creds

  externalClusters:
    - name: cluster-backup
      barmanObjectStore:
        destinationPath: s3://homelab-commafeed
        endpointURL: https://d322d8d4cf96aba84430eba5cc9ea9c9.r2.cloudflarestorage.com
        serverName: commafeed-db-production-cnpg-v0
        s3Credentials:
          accessKeyId:
            name: r2-creds
            key: commafeed-r2-access-key-id
          secretAccessKey:
            name: r2-creds
            key: commafeed-r2-secret-access-key

  backup:
    barmanObjectStore:
      destinationPath: s3://homelab-commafeed
      endpointURL: https://d322d8d4cf96aba84430eba5cc9ea9c9.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: r2-creds
          key: commafeed-r2-access-key-id
        secretAccessKey:
          name: r2-creds
          key: commafeed-r2-secret-access-key
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 14d

  # handy: resources can be used to trigger a redeploy
  resources:
    requests:
      memory: 600Mi

  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: commafeed-db-lb
              labels:
                cilium-lb-pool: postgres-pool
              annotations:
                external-dns.alpha.kubernetes.io/hostname: commafeed-db.6541333.xyz
            spec:
              type: LoadBalancer
