apiVersion: v1
kind: ConfigMap
metadata:
  name: msmtpd-configmap
  namespace: msmtpd
data:
  PUID: '1500'
  GUID: '1500'
  SMTP_HOST: 'smtp.gmail.com'
  SMTP_PORT: '587'
  SMTP_TLS: 'on'
  SMTP_STARTTLS: 'on'
  SMTP_TLS_CHECKCERT: 'on'
  SMTP_AUTH: 'on'
  SMTP_DOMAIN: '6541333.xyz'
  SMTP_USER: 'eochannelformal@gmail.com'
