apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rackula-ui-container-env
  namespace: rackula
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: API_WRITE_TOKEN
      remoteRef:
        key: rackula-api-write-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rackula-api-container-env
  namespace: rackula
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: RACKULA_API_WRITE_TOKEN
      remoteRef:
        key: rackula-api-write-token
    - secretKey: RACKULA_AUTH_SESSION_SECRET
      remoteRef:
        key: rackula-auth-session-secret
    - secretKey: RACKULA_OIDC_CLIENT_SECRET
      remoteRef:
        key: rackula-oidc-client-secret
