apiVersion: 'cilium.io/v2'
kind: CiliumLoadBalancerIPPool
metadata:
  name: gateway-pool
  namespace: kube-system
spec:
  blocks:
    - start: '10.134.20.100'
      stop: '10.134.20.149'
---
apiVersion: 'cilium.io/v2'
kind: CiliumLoadBalancerIPPool
metadata:
  name: postgres-pool
  namespace: kube-system
spec:
  blocks:
    - start: '10.134.20.200'
      stop: '10.134.20.249'
  serviceSelector:
    matchLabels:
      cilium-lb-pool: postgres-pool
