apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-container-env
  namespace: mosquitto
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: MQTT_PASSWORD
      remoteRef:
        key: mqtt-password
