apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zigbee2mqtt
resources:
  - ../../base/zigbee2mqtt/
  - secrets.yaml
  - routes.yaml

configMapGenerator:
  - name: zigbee2mqtt-values
    files:
      - values.yaml=values.yaml
