apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-container-env
  namespace: zigbee2mqtt
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        MQTT_USER: 'mqtt_user'
        MQTT_PASSWORD: '{{ .mqtt_password }}'
  data:
    - secretKey: mqtt_password
      remoteRef:
        key: mqtt-password
