apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litellm
resources:
  - ../../base/litellm
  - secrets.yaml
  - routes.yaml

configMapGenerator:
  - name: litellm-values
    files:
      - values.yaml=values.yaml
