apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
  namespace: litellm
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: master-key
      remoteRef:
        key: litellm-master-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-db-creds
  namespace: litellm
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
      data:
        username: 'litellm'
        password: '{{ .password }}'
  data:
    - secretKey: password
      remoteRef:
        key: litellm-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-backend-env
  namespace: litellm
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: ICA_API_URL
      remoteRef:
        key: ica-nextgen-api-url
    - secretKey: ICA_API_KEY
      remoteRef:
        key: ica-nextgen-coding-api-key
    # - secretKey: GENERIC_CLIENT_SECRET
    #   remoteRef:
    #     key: litellm-oidc-client-secret
