apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - secrets.yaml
  - ../../base/kube-prometheus-stack

configMapGenerator:
  - name: kube-prometheus-stack-values
    files:
      - values.yaml=values.yaml
configurations:
  - configmap.yaml
