apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  labels:
    app: adguard-home
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard
data:
  AdGuardHome.yaml: |
    bind_host: 0.0.0.0
    bind_port: 3000
    beta_bind_port: 0
    users: []  # Move users to secret
    language: "en"
    theme: "dark"
    dns:
      bind_hosts: 
        - 0.0.0.0
      port: 53
      ratelimit: 20
      bootstrap_dns:
        - 9.9.9.9
        - 1.1.1.2
      upstream_dns:
        - 9.9.9.9
        - 1.1.1.2
    filtering:
      protection_enabled: true
      filtering_enabled: true
      safebrowsing_enabled: true
      safesearch_enabled: true
      blocked_response_ttl: 10
    querylog:
      enabled: true
    tls:
      enabled: false
    log:
      file: ""
      max_backups: 0
      max_size: 100
      max_age: 3
      compress: false
      local_time: false
