apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: adguard-pvc
    labels:
        app: adguard-home
        app.kubernetes.io/name: adguard
        app.kubernetes.io/instance: adguard
    annotations:
        description: 'PVC for AdGuard Home configuration and data'
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 1Gi
