apiVersion: v1
kind: Service
metadata:
  name: adguard
  labels:
    cilium-lb-pool: apps-pool
  annotations:
    io.cilium/lb-ipam-pool: "apps-pool"
    io.cilium/lb-ipam-ips: "192.168.86.196"
spec:
  selector:
    app: adguard
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http-initial
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns
  type: LoadBalancer
