apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cnpg-db-production-v1-app
  namespace: cloudnative-pg
spec:
  databaseReclaimPolicy: delete
  cluster:
    name: cnpg-db-production-v1
  name: app
  owner: app
  ensure: absent
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cnpg-db-production-v1-commafeed
  namespace: cloudnative-pg
spec:
  cluster:
    name: cnpg-db-production-v1
  name: commafeed
  owner: commafeed
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cnpg-db-production-v1-forgejo
  namespace: cloudnative-pg
spec:
  cluster:
    name: cnpg-db-production-v1
  name: forgejo
  owner: forgejo
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cnpg-db-production-v1-authelia
  namespace: cloudnative-pg
spec:
  cluster:
    name: cnpg-db-production-v1
  name: authelia
  owner: authelia
