apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-db-production-v1
  namespace: cloudnative-pg
spec:
  immediate: true
  schedule: "0 0 3 * * *" # Go cron package format, back up at 3AM
  backupOwnerReference: cluster
  cluster:
    name: cnpg-db-production-v1
