apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: r2-creds
  namespace: cloudnative-pg
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: cnpg-r2-access-key-id
      remoteRef:
        key: cnpg-r2-access-key-id
    - secretKey: cnpg-r2-secret-access-key
      remoteRef:
        key: cnpg-r2-secret-access-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-superuser-creds
  namespace: cloudnative-pg
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: password
      remoteRef:
        key: cnpg-superuser-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: commafeed-db-creds
  namespace: cloudnative-pg
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
      data:
        username: 'commafeed'
        password: '{{ .password }}'
  data:
    - secretKey: password
      remoteRef:
        key: commafeed-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db-creds
  namespace: cloudnative-pg
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
      data:
        username: 'forgejo'
        password: '{{ .password }}'
  data:
    - secretKey: password
      remoteRef:
        key: forgejo-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-db-creds
  namespace: cloudnative-pg
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
      data:
        username: 'authelia'
        password: '{{ .password }}'
  data:
    - secretKey: password
      remoteRef:
        key: authelia-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-db-creds
  namespace: cloudnative-pg
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
      data:
        username: 'openwebui'
        password: '{{ .password }}'
  data:
    - secretKey: password
      remoteRef:
        key: openwebui-db-password
