apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 1h
  url: oci://ghcr.io/berriai/litellm/chart/litellm
  ref:
    tag: '1.93.0'
