apiVersion: apps/v1
kind: Deployment
metadata:
  name: msmtpd
  namespace: msmtpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msmtpd
  template:
    metadata:
      labels:
        app: msmtpd
    spec:
      containers:
        - name: msmtpd
          image: crazymax/msmtpd:1.8.32
          imagePullPolicy: IfNotPresent

          # Need root for s6-overlay
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault

          ports:
            - containerPort: 2500
              protocol: TCP

          livenessProbe:
            tcpSocket:
              port: 2500
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 2500
            initialDelaySeconds: 5
            periodSeconds: 10

          envFrom:
            - configMapRef:
                name: msmtpd-configmap
            - secretRef:
                name: msmtpd-container-env
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 64Mi
              cpu: 100m
