apiVersion: batch/v1
kind: CronJob
metadata:
  name: its-mytabs-rclone-scheduler
  namespace: its-mytabs
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: rclone
            image: rclone/rclone:1.74

            envFrom:
            - configMapRef:
                name: rclone-config
            - secretRef:
                name: rclone-container-env

            command: ["rclone"]
            args:
              - sync
              - /app/data/
              - "crypt:"
              - "--update"
              - "--size-only"
              - "--use-server-modtime"
              - "--transfers=4"

            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault

            volumeMounts:
            - name: its-mytabs-data
              mountPath: /app/data/

          restartPolicy: OnFailure

          volumes:
          - name: its-mytabs-data
            persistentVolumeClaim:
              claimName: its-mytabs-data
