apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-pool
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.100.191"
      stop: "192.168.100.195"

  serviceSelector:
    matchLabels:
      cilium.io/ingress: "true"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: apps-pool
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.100.196"
      stop: "192.168.100.210"

  serviceSelector:
    matchLabels:
      cilium-lb-pool: apps-pool
