apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - release.yaml
  - repository.yaml
  - ip-pool.yaml
  - l2policy.yaml

configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=values.yaml

configurations:
  - configmap.yaml
