apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-configmap
  namespace: pgadmin
data:
  PGADMIN_LISTEN_PORT: "3004"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: pgadmin
data:
  RCLONE_CONFIG_R2_TYPE: "s3"
  RCLONE_CONFIG_R2_PROVIDER: "Cloudflare"
  RCLONE_CONFIG_R2_ENDPOINT: "https://d322d8d4cf96aba84430eba5cc9ea9c9.r2.cloudflarestorage.com"
  RCLONE_CONFIG_CRYPT_TYPE: "crypt"
  RCLONE_CONFIG_CRYPT_REMOTE: "r2:homelab-rclone-backup/pgadmin/production/data"
  RCLONE_VERBOSE: "1"
