apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-container-env
  namespace: pgadmin
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: pgadmin-email
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: pgadmin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-container-env
  namespace: pgadmin
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: RCLONE_CONFIG_R2_ACCESS_KEY_ID
      remoteRef:
        key: rclone-r2-access-key-id
    - secretKey: RCLONE_CONFIG_R2_SECRET_ACCESS_KEY
      remoteRef:
        key: rclone-r2-secret-access-key
    - secretKey: RCLONE_CONFIG_CRYPT_PASSWORD
      remoteRef:
        key: pgadmin-rclone-encrypt-password

