apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudflared
  namespace: commafeed
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
