apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-db-restore-test-cnpg-v1
spec:
  imageName: quay.io/enterprisedb/postgresql:17.7
  instances: 1

  postgresql:
    parameters:
      synchronous_commit: "off"

  storage:
    size: 5Gi

  bootstrap:
    recovery:
      source: cluster-backup
      database: commafeed
      owner: commafeed
      secret:
        name: commafeed-db-creds

  externalClusters:
    - name: cluster-backup
      barmanObjectStore:
        destinationPath: s3://homelab-commafeed
        endpointURL: https://d322d8d4cf96aba84430eba5cc9ea9c9.r2.cloudflarestorage.com
        serverName: commafeed-db-production-cnpg-v1
        s3Credentials:
          accessKeyId:
            name: commafeed-r2-creds
            key: commafeed-r2-access-key-id
          secretAccessKey:
            name: commafeed-r2-creds
            key: commafeed-r2-secret-access-key

  resources:
    requests:
      memory: 600Mi

  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: commafeed-db-test-lb
              labels:
                cilium-lb-pool: postgres-pool
              annotations:
                external-dns.alpha.kubernetes.io/hostname: commafeed-db-test.6541333.xyz
            spec:
              type: LoadBalancer