apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hoppscotch-container-env
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: DATA_ENCRYPTION_KEY
      remoteRef:
        key: hoppscotch-encryption-key
