apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma

  template:
    metadata:
      labels:
        app: uptime-kuma
        try: "0"
        policy-type: "app"

    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:2.4.0

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          envFrom:
            - secretRef:
                name: uptime-kuma-container-env

          ports:
            - containerPort: 3001
              protocol: TCP

          volumeMounts:
            - mountPath: /app/data
              name: uptime-kuma-data

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      restartPolicy: Always

      volumes:
        - name: uptime-kuma-data
          persistentVolumeClaim:
            claimName: uptime-kuma-data

