apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - storage.yaml

configMapGenerator:
  - name: rackula-auth-patch
    files:
      - config.ts=patches/config.ts
  - name: rackula-nginx-patch
    files:
      - patches.conf=patches/nginx-patches.conf
