apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirling-pdf

  template:
    metadata:
      labels:
        app: stirling-pdf
        try: "0"
        policy-type: "app"

    spec:
      containers:
        - name: stirling-pdf
          image: stirlingtools/stirling-pdf:1.1.0

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: stirling-pdf-configmap
            - secretRef:
                name: stirling-pdf-container-env

          ports:
            - containerPort: 8083
              protocol: TCP

          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1"

      restartPolicy: Always
