apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirling-pdf

  template:
    metadata:
      labels:
        app: stirling-pdf
        try: "0"
        policy-type: "app"

    spec:
      containers:
        - name: stirling-pdf
          image: stirlingtools/stirling-pdf:2.11.0

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - SETUID
                - SETGID
            seccompProfile:
              type: RuntimeDefault

          envFrom:
            - configMapRef:
                name: stirling-pdf-configmap
            - secretRef:
                name: stirling-pdf-container-env

          ports:
            - containerPort: 8083
              protocol: TCP

          volumeMounts:
            - mountPath: /configs
              name: stirling-pdf-data
            - mountPath: /tmp
              name: tmp-volume
            - mountPath: /logs
              name: logs-volume
            - mountPath: /pipeline
              name: pipeline-volume
            - mountPath: /customFiles
              name: customfiles-volume

          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1"
              ephemeral-storage: "5Gi"

      restartPolicy: Always

      volumes:
        - name: stirling-pdf-data
          persistentVolumeClaim:
            claimName: stirling-pdf-data
        - name: tmp-volume
          emptyDir: {}
        - name: logs-volume
          emptyDir: {}
        - name: pipeline-volume
          emptyDir: {}
        - name: customfiles-volume
          emptyDir: {}

