capabilities:
  configurationScan: enable
  continuousScan: enable
  # runtimeDetection: enable
  vulnerabilityScan: enable
  prometheusExporter: enable

persistence:
  storageClass: 'local-path'
  accessMode: ReadWriteOnce
  size:
    backingStorage: 1Gi
    kubevuln: 1Gi

kubescape:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

# nodeAgent:
#   config:
#     prometheusExporter: enable
#   serviceMonitor:
#     enable: true

kubescapeScheduler:
  scanSchedule: '0 0 * * *'
  successfulJobsHistoryLimit: 1

kubevulnScheduler:
  scanSchedule: '0 0 * * *'
  successfulJobsHistoryLimit: 1

registryScanScheduler:
  scanSchedule: '0 0 * * *'
  successfulJobsHistoryLimit: 1
