apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed

  template:
    metadata:
      labels:
        app: commafeed
        try: "0"
        policy-type: "app"

    spec:
      containers:
        - name: commafeed
          image: athou/commafeed:4.6.0

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: commafeed-configmap
            - secretRef:
                name: commafeed-container-env

          ports:
            - containerPort: 8082
              protocol: TCP

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      restartPolicy: Always
