apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: commafeed-container-env
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: QUARKUS_DATASOURCE_USERNAME
      remoteRef:
        key: commafeed-db-username
    - secretKey: QUARKUS_DATASOURCE_PASSWORD
      remoteRef:
        key: commafeed-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: credentials.json
      remoteRef:
        key: cloudflare-tunnel-commafeed
